### ISSUE TITLE
Some objects cannot be evaluated

### ISSUE THREAD

**Issue by QtEngineer** [edgar-tr/patchnets#8]
I noticed that some .obj files of ShapeNetV2 cannot be correctly evaluateed. They can be generated when [generate_meshes = True] on useful_scripts.py ,but an error will happen when evaluate_patch_network_metrics runs again with  [generate_meshes = False]

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "useful_scripts.py", line 1101, in _evaluate_object
    iou = intersection_over_union(groundtruth_mesh_file, regressed_trimesh)
  File "useful_scripts.py", line 1028, in intersection_over_union
    watertight_result = precompute_iou_on_watertight(groundtruth_mesh_file, num_points=num_points) # num_points x 4 (x,y,z, 1.0f if inside else 0.0f)
  File "useful_scripts.py", line 1013, in precompute_iou_on_watertight
    max_bb, min_bb = _get_bounding_box(groundtruth_trimesh.vertices)
AttributeError: 'Scene' object has no attribute 'vertices'

Is it because  these objects are nor water-tight? And how to fix it?

**Comment by QtEngineer** [comment]
I print all attributes and found .obj files loaded by trimesh  does not contain attr 'vertcis'
 ['__abstractmethods__', '__add__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_cache', '_hashable', '_lights', 'add_geometry', 'apply_obb', 'apply_scale', 'apply_transform', 'apply_translation', 'area', 'bounding_box', 'bounding_box_oriented', 'bounding_cylinder', 'bounding_primitive', 'bounding_sphere', 'bounds', 'bounds_corners', 'camera', 'camera_rays', 'camera_transform', 'centroid', 'convert_units', 'convex_hull', 'copy', 'crc', 'deduplicated', 'delete_geometry', 'dump', 'duplicate_nodes', 'explode', 'export', 'extents', 'geometry', 'geometry_identifiers', 'graph', 'has_camera', 'is_empty', 'is_valid', 'lights', 'md5', 'metadata', 'rezero', 'save_image', 'scale', 'scaled', 'set_camera', 'show', 'subscene', 'triangles', 'triangles_node', 'units']
